services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3000"
    env_file:
      - env/.env.production
    restart: unless-stopped
    networks:
      - dmw-shared

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx-stage
    ports:
      - "8080:80"
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - dmw-shared

networks:
  dmw-shared:
    external: true