services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001-3003:3000" # Map host ports 3001, 3002, and 3003 to container port 3000
    env_file:
      - env/.env.development # Load environment variables from env folder
    restart: unless-stopped