services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api-stage  # <--- THIS TELLS DOCKER TO STOP AT THE API STAGE
    ports:
      - "3001-3003:3000"
    env_file:
      - env/.env.production
    restart: unless-stopped