events { 
    worker_connections 1024; 
}

http {
    upstream api_backend {
        # Docker's internal DNS automatically resolves 'api' to the IPs of all 3 replicas
        server api:3000;
    }

    server {
        listen 80;
        
        location / {
            proxy_pass http://api_backend;
        }
    }
}